### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by dotnet236** [comment]
@kuraga think you've made a mistake here.

**Comment by kuraga** [comment]
@dotnet236 no, just these commits happen long time ago...

**Comment by dotnet236** [comment]
@kuraga why issue a PR to my fork?

**Comment by kuraga** [comment]
Hm... I didn't remember :smile: It was forward, maybe :smile: BTW, I've created my own lib: https://github.com/kuraga/aloha-rails-improved. It was long time ago, tooo....

**Pull request closed without merging**
